### ISSUE TITLE
Crear modulo

### ISSUE THREAD

**Issue by leonelgoncalves** [Programa-TrainIT-Ar/plataforma#20]
## Feature Crear modulo

Crear formulario para crear modulo 

![Screenshot 2023-12-18 181720](https://github.com/Programa-TrainIT-Ar/plataforma/assets/5423484/29be6097-cced-471a-b662-b3f5dc3da6ca)

Al llenar los campos y presionar el boton crear se debe hacer una llamada con RTK Query. Al concluir hay que refrescar la lista de los modulos y redireccionar a la lista de modulos.

**Comment by Aramis09** [comment]
Leonel, aqui tengo algunas dudas.  Yo habia hecho la conexion con la api sin RTK query, porque lo hice antes de que se cree esto.

Mi duda es si quieres que trabajemos con los modulos de forma global ? es decir quires que la accion de crear modulo este manejada por redux ? por ahora lo tengo implementado sin redux, por favor cuando puedas mira el codigo
